/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface TreasureMapGeneratorInterface extends utils.Interface {
  functions: {
    "tokenURI(uint256,string,string,bytes3)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish, string, string, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;

  events: {};
}

export interface TreasureMapGenerator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TreasureMapGeneratorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    tokenURI(
      tokenId: BigNumberish,
      mapType: string,
      range: string,
      color: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  tokenURI(
    tokenId: BigNumberish,
    mapType: string,
    range: string,
    color: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    tokenURI(
      tokenId: BigNumberish,
      mapType: string,
      range: string,
      color: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    tokenURI(
      tokenId: BigNumberish,
      mapType: string,
      range: string,
      color: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    tokenURI(
      tokenId: BigNumberish,
      mapType: string,
      range: string,
      color: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
