/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { ERC721Holder, ERC721HolderInterface } from "../ERC721Holder";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "onERC721Received",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102d3806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063150b7a0214610030575b600080fd5b61006761003e366004610106565b7f150b7a0200000000000000000000000000000000000000000000000000000000949350505050565b6040516100749190610185565b60405180910390f35b600061009061008b846101cf565b6101b3565b9050828152602081018484840111156100ab576100ab600080fd5b6100b6848285610218565b509392505050565b80356100c981610280565b92915050565b600082601f8301126100e3576100e3600080fd5b81356100f384826020860161007d565b949350505050565b80356100c981610297565b6000806000806080858703121561011f5761011f600080fd5b600061012b87876100be565b945050602061013c878288016100be565b935050604061014d878288016100fb565b925050606085013567ffffffffffffffff81111561016d5761016d600080fd5b610179878288016100cf565b91505092959194509250565b7fffffffff0000000000000000000000000000000000000000000000000000000082168152602081016100c9565b60006101be60405190565b90506101ca8282610224565b919050565b600067ffffffffffffffff8211156101e9576101e9610251565b601f19601f83011660200192915050565b600073ffffffffffffffffffffffffffffffffffffffff82166100c9565b82818337506000910152565b601f19601f830116810181811067ffffffffffffffff8211171561024a5761024a610251565b6040525050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052604160045260246000fd5b610289816101fa565b811461029457600080fd5b50565b8061028956fea26469706673582212202fb2f713b306d6db7ca63b86df39b5594adfd8db268a524f7e9a80e39c883d8264736f6c63430008070033";

type ERC721HolderConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ERC721HolderConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ERC721Holder__factory extends ContractFactory {
  constructor(...args: ERC721HolderConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ERC721Holder> {
    return super.deploy(overrides || {}) as Promise<ERC721Holder>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ERC721Holder {
    return super.attach(address) as ERC721Holder;
  }
  connect(signer: Signer): ERC721Holder__factory {
    return super.connect(signer) as ERC721Holder__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ERC721HolderInterface {
    return new utils.Interface(_abi) as ERC721HolderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC721Holder {
    return new Contract(address, _abi, signerOrProvider) as ERC721Holder;
  }
}
