/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  TreasureMapGeneratorX,
  TreasureMapGeneratorXInterface,
} from "../TreasureMapGeneratorX";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "mapType",
        type: "string",
      },
      {
        internalType: "string",
        name: "range",
        type: "string",
      },
      {
        internalType: "bytes3",
        name: "color",
        type: "bytes3",
      },
    ],
    name: "tokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610318806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063d6b8e85c14610030575b600080fd5b61004861003e3660046100e7565b6060949350505050565b60405161005591906101b3565b60405180910390f35b600061007161006c846101e7565b6101cb565b90508281526020810184848401111561008c5761008c600080fd5b610097848285610212565b509392505050565b80356100aa816102aa565b92915050565b600082601f8301126100c4576100c4600080fd5b81356100d484826020860161005e565b949350505050565b80356100aa816102dc565b6000806000806080858703121561010057610100600080fd5b600061010c87876100dc565b945050602085013567ffffffffffffffff81111561012c5761012c600080fd5b610138878288016100b0565b935050604085013567ffffffffffffffff81111561015857610158600080fd5b610164878288016100b0565b92505060606101758782880161009f565b91505092959194509250565b600061018b825190565b8084526020840193506101a281856020860161021e565b601f01601f19169290920192915050565b602080825281016101c48184610181565b9392505050565b60006101d660405190565b90506101e2828261024e565b919050565b600067ffffffffffffffff8211156102015761020161027b565b601f19601f83011660200192915050565b82818337506000910152565b60005b83811015610239578181015183820152602001610221565b83811115610248576000848401525b50505050565b601f19601f830116810181811067ffffffffffffffff821117156102745761027461027b565b6040525050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052604160045260246000fd5b7fffffff000000000000000000000000000000000000000000000000000000000081165b81146102d957600080fd5b50565b806102ce56fea26469706673582212209242d1712f207847a595e87e0ba95ffbf0671efa24ab60d7ed837e0da14e9ca564736f6c63430008070033";

type TreasureMapGeneratorXConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TreasureMapGeneratorXConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TreasureMapGeneratorX__factory extends ContractFactory {
  constructor(...args: TreasureMapGeneratorXConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<TreasureMapGeneratorX> {
    return super.deploy(overrides || {}) as Promise<TreasureMapGeneratorX>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): TreasureMapGeneratorX {
    return super.attach(address) as TreasureMapGeneratorX;
  }
  connect(signer: Signer): TreasureMapGeneratorX__factory {
    return super.connect(signer) as TreasureMapGeneratorX__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TreasureMapGeneratorXInterface {
    return new utils.Interface(_abi) as TreasureMapGeneratorXInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TreasureMapGeneratorX {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as TreasureMapGeneratorX;
  }
}
